// src/app/Components/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { SaveUserService } from 'src/app/services/save-user.service';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { RegisterService } from 'src/app/services/register.service';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { MustMatch } from 'src/app/_helpers';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {

  addUser: any = {};
  comboBoxesDataGender: any;
  registerForm: FormGroup;
  submitted = false;

  gender: any = [{
    gender_id: 1,
    gender: 'male'
  },
  {
    gender_id: 2,
    gender: 'female'
  },
];
  constructor( private saveUserService: RegisterService,
    private router: Router,
    private toastr: ToastrService,
    private formBuilder: FormBuilder,) { }

  ngOnInit() {
    this.registerForm = this.formBuilder.group({
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      genderId: ['', Validators.required],
      contactNumber: ['', [Validators.required,]],
      email: ['', [Validators.required, Validators.email]],
      address: ['', Validators.required],
      company: ['', Validators.required],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required]
  } ,{
    validator: MustMatch('password', 'confirmPassword')
  });
  }

  get f() { return this.registerForm.controls; }

  saveUser() {
    this.submitted = true;
    if (this.registerForm.invalid) {
            return;
    }
    this.addUser.createdBy = '';
    this.addUser.userStatusId = '1';
    this.addUser.roleId = '4';
    this.saveUserService.saveuser(this.addUser).subscribe(
      (data: any) => {
        console.log('register', data);
        console.log(data.message)
        if (data && data.resultsMap && data.resultsMap.user) {
          this.toastr.success('Registration Successfully');
          this.router.navigateByUrl('/app-dashboard');
        } 
      },
      error => {
        console.log(error)
        if(error)
        this.toastr.warning(error);
      }
    );
  }

  // loadComboBoxes() {
  //   const body = [
  //     'roles',
  //     'bookGenre',
  //     'gender',
  //     'bookCondition',
  //     'userStatus'
  //   ];
  //   this.saveUserService.loadComboDropDowns(body).subscribe(
  //     (data: any) => {
  //       if (data) {
  //         // console.log('comboDropDowns', data);
  //         this.comboBoxesDataGender = data.result.gender;
  //         console.log('gender',this.comboBoxesDataGender)
  //       }
  //     },
  //     error => {
  //       this.toastr.warning(error.error.message);
  //     }
  //   );
  // }

  comboGender($event, id): void {
    if ($event.source.selected) {
      this.addUser.genderId = id.gender_id;
    }
  }

}



<div class="split left">
    <p class="About-WiseReads">About WiseReads</p>
    <div class="content-box">
        <p class="content">Wisereads is proud to introduce one of the most awaited and affordable book rental platform for
                individuals, kids, students, and corporates across the country. Wisereads Book Rental Library provides
                hassle-free availability of books at a very affordable price.
        </p>

        <mat-card class="example-card">
            <mat-card-header>
                <mat-card-title class="bottom-contact">
                    <h5>Support</h5>
                    <div mat-card-avatar class="example-header-image"></div>
                </mat-card-title>
                <!-- <mat-card-subtitle>Dog Breed</mat-card-subtitle> -->
            </mat-card-header>

            <mat-card-content>
                <div class="cnt-spt">
                    Call: 9354533923 <br> Email: support@wisereads.in
                </div>
            </mat-card-content>
        </mat-card>
    </div>


</div>

<div class="split right">
    <div class="centered">

        <div class="wiseReads-box">
            <!-- <img mat-card-image src="https://material.angular.io/assets/img/examples/shiba2.jpg" alt="Photo of a Shiba Inu"> -->
            <div class="login-heading">
                
                <img src="../../../assets/images/wiseReads.svg" style="width: 230px;border-radius: 0PX;">
                <p class="Login">Register</p>
            </div>
            <div class="form1">
              
                <form class="registration-form"  [formGroup]="registerForm" >
                    <div class="row" >
                      <div class="col-md-6 mt-4">
                            <input 
                              placeholder="First Name"
                              type="text"
                              name="firstName"
                              [(ngModel)]="addUser.firstName"
                              pattern="^[a-zA-Z0-9- ]{1,30}$"
                              required
                              formControlName="firstName"
                              class="form-control" 
                              [ngClass]="{ 'is-invalid': submitted && f.firstName.errors }"
                            />
                            <div *ngIf="submitted && f.firstName.errors" class="invalid-feedback">
                                  <div *ngIf="f.firstName.errors.required">First Name is required</div>
                            </div>
                      </div>
        
                      <div class="col-md-6 mt-4">
                              <input 
                                placeholder="Last Name"
                                type="text"
                                name="lastName"
                                [(ngModel)]="addUser.lastName"
                              
                                pattern="^[a-zA-Z0-9- ]{1,30}$"
                                required
                                formControlName="lastName" 
                                class="form-control" 
                                [ngClass]="{ 'is-invalid': submitted && f.lastName.errors }"
                              />
                              <div *ngIf="submitted && f.lastName.errors" class="invalid-feedback">
                                    <div *ngIf="f.lastName.errors.required">Last Name is required</div>
                              </div>
                      </div>
        
                      <div class="col-md-6 mt-4">
                            <select placeholder="Select Gender" 
                                    class="login-fields"
                                    name="genderId" 
                                    id="genderId" 
                                    [(ngModel)]="addUser.genderId" 
                                    formControlName="genderId" 
                                    class="form-control" 
                                    [ngClass]="{ 'is-invalid': submitted && f.genderId.errors }" 
                            >
                                    <option value="undefined" hidden>Gender</option>
                                    <option *ngFor="let id of gender" [value]="id.gender_id" (onSelectionChange)="comboGender($event,id)">             
                                        {{id.gender}}
                                    </option>
                            </select>
                            <div *ngIf="submitted && f.genderId.errors" class="invalid-feedback">
                                <div *ngIf="f.genderId.errors.required">Please select Gender</div>
                            </div>
                      </div>
        
                      <div class="col-md-6 mt-4">
                              <input
                                placeholder="Phone Number"
                                name="contactNumber"
                                [(ngModel)]="addUser.contactNumber"
                                class="login-fields"
                                pattern="^[0-9-]{10}$"
                                required
                                formControlName="contactNumber" 
                                class="form-control" 
                                [ngClass]="{ 'is-invalid': submitted && f.contactNumber.errors }"
                              />
                              <div *ngIf="submitted && f.contactNumber.errors" class="invalid-feedback">
                                    <div *ngIf="f.contactNumber.errors.required">Phone Number is required</div>
                                    <div *ngIf="f.contactNumber.errors.pattern">Phone Number is incorrect</div>
                              </div>
                      </div>
                      
                      <div class="col-md-6 mt-4">
                          <textarea
                            class="login-fields"
                            placeholder="House Address"
                            type="text"
                            name="address"
                            [(ngModel)]="addUser.address"
                            required
                            formControlName="address" 
                            class="form-control" 
                            style="height: 100px;"
                            [ngClass]="{ 'is-invalid': submitted && f.address.errors }"
                          ></textarea>
                          <div *ngIf="submitted && f.address.errors" class="invalid-feedback">
                                <div *ngIf="f.address.errors.required">Address is required</div>
                          </div>
                  </div>
                      <div class="col-md-6 mt-4">
                        <div class="row">
              
                          <div class="col-md-12 ">
                                  <input
                                    class="login-fields"
                                    placeholder="Company Name"
                                    type="text"
                                    name="company"
                                    [(ngModel)]="addUser.company"
                                    pattern="^[a-zA-Z0-9- ]{1,30}$"
                                    required
                                    formControlName="company" 
                                    class="form-control" 
                                    [ngClass]="{ 'is-invalid': submitted && f.company.errors }"
                                  />
                                  <div *ngIf="submitted && f.company.errors" class="invalid-feedback">
                                        <div *ngIf="f.company.errors.required">Company Name is required</div>
                                  </div>
                        
                          </div>

                          <div class="col-md-12 mt-4">
                              <input
                              class="login-fields"
                              placeholder="Email"
                              type="text"
                              name="email"
                              [(ngModel)]="addUser.email"
                              required
                              email
                              formControlName="email" 
                              class="form-control" 
                              [ngClass]="{ 'is-invalid': submitted && f.email.errors }"
                            />
                            <div *ngIf="submitted && f.email.errors" class="invalid-feedback">
                                  <div *ngIf="f.email.errors.required">Email is required</div>
                            </div>
                          </div>
                        </div>
                              
                      </div>
        
                      <div class="col-md-6 mt-4">
                        
                              <input
                                class="login-fields"
                                placeholder="Password"
                                type="password"
                                name="password"
                                [(ngModel)]="addUser.password"
                                required
                                formControlName="password" 
                                class="form-control" 
                                [ngClass]="{ 'is-invalid': submitted && f.password.errors }"
                              />
                              <div *ngIf="submitted && f.password.errors" class="invalid-feedback">
                                    <div *ngIf="f.password.errors.required">Passwords is required</div>
                                    <div *ngIf="f.password.errors.minlength">Password must be at least 6 characters</div>
                              </div>
                      </div>
        
                      <div class="col-md-6 mt-4">
                              <input
                                class="login-fields"
                                placeholder="Confirm Password"
                                type="password"
                                name="confirmPassword"
                                required
                                formControlName="confirmPassword" 
                                class="form-control" 
                                [ngClass]="{ 'is-invalid': submitted && f.confirmPassword.errors }"
                              />
                              <div *ngIf="submitted && f.confirmPassword.errors" class="invalid-feedback">
                                    <div *ngIf="f.confirmPassword.errors.required">Confirm Password is required</div>
                                    <div *ngIf="f.confirmPassword.errors.mustMatch">Passwords must match</div>
                              </div>
                          
                      </div>
        
                      <div class="col-md-12 mt-4" style="display: flex;justify-content: flex-start;align-items: center;">
                        <a routerLink="/login"> Already a user: Login&nbsp;&nbsp;<i class="fa fa-sign-in" aria-hidden="true"></i></a>
                          <button mat-raised-button  
                                  (click)="saveUser()"  
                                  style=" width: 7vw;
                                  height: 40px;
                                  margin-left: auto;
                                  background-image: linear-gradient(to bottom, #6fe3ff, #2fc7f5);"
                                  class="mat-raised-button mat-primary">Register</button>
                      </div>  
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

// src/app/components/register/Register.jsx
import React, { useState, useEffect } from "react";
import AboutWiseReads from "../commons/AboutWisereads";
import WiseReadsLogo from "../../../assets/images/wiseReads.svg";
import "../../../assets/css/registration.css";
import useRegisterForm from "../../hooks/login/useFormValidation";
import { validateRegistration } from "../../hooks/register/registerFormValidations";
import RegisterService from "../../services/registrationservice";
import { BOOTSTRAP_ALERT_CLASS } from "../../stores/constants";
import { Redirect } from "react-router-dom";

const Register = () => {
  const genderList = [
    {
      gender_id: 1,
      gender: "male"
    },
    {
      gender_id: 2,
      gender: "female"
    }
  ];

  const [registerMsg, setRegisterMsg] = useState("");
  const [registerMsgClass, setRegisterClass] = useState("");
  const [registerSuccess, setRegisterSuccess] = useState(false);

  const registerNewUser = () => {
    const user = { ...values };
    setRegisterMsg("");
    setRegisterClass("");
    delete user["confirmPassword"];
    user.roleId = 4;
    user.userStatusId = 1;
    user.createdBy = user.email;
    console.log(JSON.stringify(user));
    RegisterService.registerNewUser(user)
      .then(response => {
        console.log(JSON.stringify(response));
        const {
          data: { message }
        } = response;
        //setRegisterMsg(message);
        setRegisterMsg(message + ", Please login to continue...");
        setRegisterClass(BOOTSTRAP_ALERT_CLASS + "success");

        setTimeout(() => {
          setRegisterSuccess(true);
        }, 1500);
      })
      .catch(error => {
        setRegisterMsg(error["data"]["errors"]["email"]["emailAlreadyExists"]);
        setRegisterClass(BOOTSTRAP_ALERT_CLASS + "danger");
        console.log(JSON.stringify(error));
      });
  };

  useEffect(() => {
    if (registerSuccess) {
      redirectToHome();
    }
  }, [registerSuccess]);

  const { values, errors, handleSubmit, handleInput } = useRegisterForm(
    {
      firstName: "",
      lastName: "",
      email: "",
      address: "",
      contactNumber: "",
      genderId: "",
      userStatusId: "",
      password: "",
      confirmPassword: "",
      roleId: "",
      companyName: ""
    },
    registerNewUser,
    validateRegistration
  );
  const redirectToHome = () => {
    console.log("In redirect to lgoin");
    return <Redirect to="/login" />;
  };

  if (registerSuccess) {
    return redirectToHome();
  }
  return (
    <div>
      <div className="split-left">
        <AboutWiseReads />
      </div>
      <div className="split-right">
        <div className="centered">
          <div className="wiseReads-box">
            <div className="login-heading">
              <img
                alt="Wise reads logo"
                src={WiseReadsLogo}
                className="wiseReadsLogo"
              />
              <p className="Login">Register</p>
            </div>
            <div className="form1">
              {registerMsg && (
                <div className={registerMsgClass}>{registerMsg}</div>
              )}
              <form onSubmit={handleSubmit}>
                <div className="row">
                  <div className="col-md-6 mt-4">
                    <input
                      placeholder="First Name"
                      type="text"
                      name="firstName"
                      className="form-control"
                      onChange={handleInput}
                      onBlur={handleInput}
                      value={values.firstName || ""}
                    />
                    <div className="errorMessages">
                      <div>{errors.firstName && errors.firstName}</div>
                    </div>
                  </div>
                  <div className="col-md-6 mt-4">
                    <input
                      placeholder="Last Name"
                      type="text"
                      name="lastName"
                      className="form-control"
                      onChange={handleInput}
                      onBlur={handleInput}
                      value={values.lastName || ""}
                    />
                    <div className="errorMessages">
                      <div>{errors.lastName && errors.lastName}</div>
                    </div>
                  </div>
                  <div className="col-md-6 mt-4">
                    <select
                      placeholder="Select Gender"
                      name="genderId"
                      id="genderId"
                      className="form-control"
                      onChange={handleInput}
                      onBlur={handleInput}
                      value={values.genderId || ""}
                    >
                      <option value="" hidden>
                        -- Select gender --
                      </option>
                      {genderList.map(gender => {
                        return (
                          <option value={gender.gender_id}>
                            {gender.gender}
                          </option>
                        );
                      })}
                    </select>
                    <div className="errorMessages">
                      <div>{errors.genderId && errors.genderId}</div>
                    </div>
                  </div>

                  <div className="col-md-6 mt-4">
                    <input
                      placeholder="Phone Number"
                      name="contactNumber"
                      className="form-control"
                      pattern="^[0-9-]{10}$"
                      onChange={handleInput}
                      onBlur={handleInput}
                      value={values.contactNumber || ""}
                    />
                    <div className="errorMessages">
                      <div>{errors.contactNumber && errors.contactNumber}</div>
                    </div>
                  </div>
                  <div className="col-md-6 mt-4">
                    <textarea
                      placeholder="House Address"
                      type="text"
                      name="address"
                      className="form-control reg-address"
                      onChange={handleInput}
                      onBlur={handleInput}
                      value={values.address || ""}
                    />
                    <div className="errorMessages">
                      <div>{errors.address && errors.address}</div>
                    </div>
                  </div>

                  <div className="col-md-6 mt-4">
                    <div className="row">
                      <div className="col-md-12 ">
                        <input
                          className="form-control"
                          placeholder="Company Name"
                          type="text"
                          name="companyName"
                          onChange={handleInput}
                          onBlur={handleInput}
                          value={values.companyName || ""}
                        />
                        <div className="errorMessages">
                          <div>{errors.companyName && errors.companyName}</div>
                        </div>
                      </div>

                      <div className="col-md-12 mt-4">
                        <input
                          className="form-control"
                          placeholder="Email"
                          type="text"
                          name="email"
                          onChange={handleInput}
                          onBlur={handleInput}
                          value={values.email || ""}
                        />
                        <div className="errorMessages">
                          <div>{errors.email && errors.email}</div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="col-md-6 mt-4">
                    <input
                      className="form-control"
                      placeholder="Password"
                      type="password"
                      name="password"
                      formControlName="password"
                      onChange={handleInput}
                      onBlur={handleInput}
                      value={values.password || ""}
                    />
                    <div className="errorMessages">
                      <div>{errors.password && errors.password}</div>
                    </div>
                  </div>

                  <div className="col-md-6 mt-4">
                    <input
                      className="form-control"
                      placeholder="Confirm Password"
                      type="password"
                      name="confirmPassword"
                      onChange={handleInput}
                      onBlur={handleInput}
                      value={values.confirmPassword || ""}
                    />
                    <div className="errorMessages">
                      <div>
                        {errors.confirmPassword && errors.confirmPassword}
                      </div>
                    </div>
                  </div>

                  <div className="col-md-12 mt-4 already-user-login">
                    <a routerLink="/login">
                      {" "}
                      Already a user: Login&nbsp;&nbsp;
                      <i className="fa fa-sign-in" aria-hidden="true" />
                    </a>
                    <button
                      mat-raised-button
                      className="mat-raised-button mat-primary register-btn"
                      type="submit"
                    >
                      Register
                    </button>
                  </div>
                </div>
              </form>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;
